config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }

  resources :movie_theaters do
    resources :reviews, except: [:index, :show]
  end

  resources :reviews, except: [:index, :show] do
    resources :votes, only: [:upvote, :downvote] do
      collection do
        post :upvote
        post :downvote
      end
    end
  end

  resources :searches, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :votes, only: [:upvote, :downvote] do
        collection do
          post :upvote
          post :downvote
        end
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  root 'movie_theaters#index'
end

app/models/movie_theater.rb
class MovieTheater < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :state
  belongs_to :user

  validates :name, presence: true
  validates :city, presence: true
  validates :state_id, presence: true
  validates :zipcode, length: { is: 5, allow_nil: true, allow_blank: true }
  validates :user_id, presence: true
  validates :website, url: { allow_nil: true, allow_blank: true }

  def rating
    sum = reviews.sum(:rating)
    count = reviews.where.not(rating: 0).count
    if count > 0
      average = sum.to_f / count
      average.round(1)
    else
      0
    end
  end
end

app/controllers/movie_theaters_controller.rb
class MovieTheatersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update]
  before_action :define_states, only: [:new, :create, :edit, :update]
  before_action :authorize_admin, only: [:destroy]

  def index
    @movie_theaters = MovieTheater.all
  end

  def show
    @movie_theater = MovieTheater.find(params[:id])
  end

  def new
    @movie_theater = MovieTheater.new
  end

  def create
    @movie_theater = MovieTheater.new(movie_theater_params)
    @movie_theater.user = current_user

    if @movie_theater.save
      redirect_to @movie_theater, notice: 'New Movie Theater Added!'
    else
      flash.now[:alert] = @movie_theater.errors.full_messages
      render :new
    end
  end

  def edit
    @movie_theater = MovieTheater.find(params[:id])
  end

  def update
    @movie_theater = MovieTheater.find(params[:id])
    if @movie_theater.update(movie_theater_params)
      redirect_to @movie_theater, notice: "Movie Theater Updated!"
    else
      flash.now[:alert] = @movie_theater.errors.full_messages
      render :edit
    end
  end

  def destroy
    @movie_theater = MovieTheater.find(params[:id])
    @movie_theater.destroy
    flash[:notice] = "Movie Theater Deleted."
    redirect_to movie_theaters_path
  end

  private

  def define_states
    @states ||= State.all
  end

  def movie_theater_params
    params.require(:movie_theater).permit(:name, :address, :city, :state_id, :zipcode, :website)
  end

  def authorize_user
    movie_theater = MovieTheater.find(params[:id])
    if !user_signed_in? || current_user != movie_theater.user
      redirect_to movie_theater, alert: "You Can Only Update Theaters You've Added!"
    end
  end

  def authorize_admin
    if !current_user || !current_user.admin?
      redirect_to root_path
    end
  end
end

app/views/movie_theaters/_form.html.erb
<%= form_for(@movie_theater) do |f| %>
  <%= render 'shared/flash_messages' if !flash.empty? %>

  <div class="form-group col-md-12">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Name of Movie Theater" %>
  </div>

  <div class="form-group col-md-12">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
  </div>

  <div class="form-group col-md-4">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control", placeholder: "City" %>
  </div>

  <div class="form-group col-md-4">
    <%= f.label :state_id %>
    <%= f.collection_select(:state_id, @states, :id, :name, {}, { class: "form-control" }) %>
  </div>

  <div class="form-group col-md-4">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode, class: "form-control", placeholder: "Zipcode" %>
  </div>

  <div class="form-group col-md-12">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control", placeholder: "Website (http://www.example.com)" %>
  </div>

  <div class="form-group col-md-12 new-edit-button-div">
    <% if action_name == "new" || action_name == "create" %>
      <%= f.submit "Add Movie Theater", class: "btn btn-primary" %>
    <% end %>
    <% if action_name == "edit" || action_name == "update" %>
      <%= f.submit "Update Movie Theater", class: "btn btn-success" %>
    <% end %>
  </div>
<% end %>

app/views/movie_theaters/edit.html.erb
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="panel panel-primary">
    <div class="panel-heading panel-form-title">
      <div class="panel-title">
        <h2>Update Movie Theater</h2>
      </div>
    </div>
    <div class="panel-body">
      <%= render "form" %>

      <div class="form-group col-md-12 back-link-div">
        <%= link_to "Back", movie_theater_path(@movie_theater) %>
      </div>
    </div>
  </div>
</div>

app/views/movie_theaters/index.html.erb
<h1>Movie Theaters</h1>

<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-8 col-xs-12">
    <%= form_tag(searches_path, method: "get") do %>
      <div class="input-group">
        <%= text_field_tag :search, nil, placeholder: "Search for Movie Theater", class: "form-control", id: "theater-search" %>
        <span class="input-group-btn">
          <%= submit_tag 'Search', class: "btn btn-default" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

<br>
<% @movie_theaters.each do |theater| %>
  <div class="row">
    <div class="col-lg-6 col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading panel-form-title">
          <h3 class="panel-title pull-left"><%= link_to theater.name, movie_theater_path(theater) %></h3>
          <% if theater.rating > 0 %>
            <p class="panel-title pull-right">Rating: <%= theater.rating %> / 5</p>
          <% end %>
          <div class="clearfix"></div>
        </div>
        <div class="panel-body">
          <div class="col-lg-6 col-md-6 col-xs-6">
            <%= "#{theater.city}, #{theater.state.abbreviation}" %>
          </div>
          <div class="pull-right">
            Reviews <span class="badge"><%= theater.reviews.count %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if @no_search_results %>
  <div class="row">
    <div class="col-lg-6 col-md-8">
      <p>We couldn't find a movie theater matching your search.</p>
      <p>You can add a new movie theater <%= link_to "HERE!", new_movie_theater_path %></p>
    </div>
  </div>
<% end %>

app/views/movie_theaters/new.html.erb
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="panel panel-primary">
    <div class="panel-heading panel-form-title">
      <div class="panel-title">
        <h2>Add Movie Theater</h2>
      </div>
    </div>
    <div class="panel-body">
      <%= form_for(@movie_theater) do |f| %>
        <%= render 'shared/flash_messages' if !flash.empty? %>

        <div class="form-group col-md-12">
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Name of Movie Theater" %>
        </div>

        <div class="form-group col-md-12">
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
        </div>

        <div class="form-group col-md-4">
          <%= f.label :city %>
          <%= f.text_field :city, class: "form-control", placeholder: "City" %>
        </div>

        <div class="form-group col-md-4">
          <%= f.label :state_id %>
          <%= f.collection_select(:state_id, @states, :id, :name, {}, { class: "form-control" }) %>
        </div>

        <div class="form-group col-md-4">
          <%= f.label :zipcode %>
          <%= f.text_field :zipcode, class: "form-control", placeholder: "Zipcode" %>
        </div>

        <div class="form-group col-md-12">
          <%= f.label :website %>
          <%= f.text_field :website, class: "form-control", placeholder: "Website (http://www.example.com)" %>
        </div>

        <div class="form-group col-md-12">
          <%= f.submit "Add Movie Theater", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/movie_theaters/show.html.erb
<div class="well well-lg col-lg-12">
  <div class="col-lg-7">
    <h2 class="theater-show-name"><%= @movie_theater.name %></h2>
    <div class="col-lg-3 no-left-padding">
      <p>
        <% if !@movie_theater.address.empty? %>
          <%= @movie_theater.address %>
          <br>
        <% end %>
        <%= "#{@movie_theater.city}, #{@movie_theater.state.abbreviation} #{@movie_theater.zipcode}" %>
      </p>
      <% if !@movie_theater.website.empty? %>
        <%= link_to "Theater's Website", url_to_external(@movie_theater.website) %>
      <% end %>
    </div>
    <div class="col-lg-3 col-lg-offset-1 no-left-padding">
      <% if @movie_theater.rating > 0 %>
        <p>Rating: <%= @movie_theater.rating %> / 5</p>
      <% end %>
    </div>
    <% if current_user == @movie_theater.user %>
      <div class="col-lg-12 no-left-padding update-theater-show-button-div">
        <%= link_to "Update Theater", edit_movie_theater_path(@movie_theater), class: "btn btn-success btn-sm" %>
      </div>
    <% end %>
    <% if current_user.try(:admin?) %>
      <div class="col-lg-12 no-left-padding update-theater-show-button-div">
        <%= button_to "Delete Theater", movie_theater_path(@movie_theater), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

<div class="col-lg-12">
  <div class="col-lg-12">
    <div class="col-lg-12">
      <h3 class="review-theater-title">Reviews</h3>
      <% if current_user && !@movie_theater.reviews.where(user: current_user).empty? %>
        <%= link_to "Update Review", edit_movie_theater_review_path(@movie_theater, @movie_theater.reviews.where(user: current_user)[0]), class: "btn btn-primary", id: "add-review-link" %>
      <% else %>
        <%= link_to "Add Review", new_movie_theater_review_path(@movie_theater), class: "btn btn-primary", id: "add-review-link" %>
      <% end %>
    </div>
  </div>
</div>
<% @movie_theater.reviews.order(updated_at: :desc).each do |review| %>
  <div class="well col-lg-8 col-md-10 review">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <h4><%= review.title %></h4>
      <% if review.rating > 0 %>
        <h5>Rating: <strong><%= review.rating %> / 5</strong></h5>
      <% end %>
      <p>
        <%= review.body %>
      </p>
      <h6>
        <strong>Review By: <%= review.user.username %></strong> - Created On:
        <%= review.created_at.strftime('%x') %>
        <% if review.updated_at.strftime('%x') != review.created_at.strftime('%x') %>
          - Updated On: <%= review.updated_at.strftime('%x') %>
        <% end %>
      </h6>
      <h6>
        <span id="vote-total-<%= review.id %>">
          <% if review.helpful_votes > 0 %>
            <%= pluralize(review.helpful_votes, 'person') %> found this review helpful.
          <% end %>
        </span>
        Did you find this review helpful? - <%= link_to "Yes", upvote_review_votes_path(review), method: :post, id: "upvote-#{review.id}", class: "upvote" %>
         or
         <%= link_to "No", downvote_review_votes_path(review), method: :post, id: "downvote-#{review.id}", class: "downvote" %>
      </h6>
      <% if current_user.try(:admin?) %>
        <div class="update-theater-show-button-div">
          <%= button_to "Delete Review", movie_theater_review_path(@movie_theater, review), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>