config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }

  resources :movie_theaters do
    resources :reviews, except: [:index, :show]
  end

  resources :reviews, except: [:index, :show] do
    resources :votes, only: [:upvote, :downvote] do
      collection do
        post :upvote
        post :downvote
      end
    end
  end

  resources :searches, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :votes, only: [:upvote, :downvote] do
        collection do
          post :upvote
          post :downvote
        end
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  root 'movie_theaters#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MovieTheaterReviews</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%= root_path %>>Movie Theater Reviews</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Movie Theaters", movie_theaters_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Add Movie Theater", new_movie_theater_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.try(:admin?) %>
              <li><%= link_to "View Users", admin_users_path %></li>
            <% end %>
            <% if !user_signed_in? %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% else %>
              <li><%= link_to "My Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if action_name == "index" || action_name == "show" || (controller_name == "registrations" && action_name == "edit") %>
      <%= render 'shared/flash_messages' %>
    <% end %>
    <div id="flash-container">
    </div>

    <div class="container" id="main-div">
      <%= yield %>
    </div>

  </body>
</html>